---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      box: chef/centos-6.5
  - name: centos-7.0
    driver:
      box: chef/centos-7.0
  - name: rhel-6.5
    driver:
      box: rhel-6.5
      box_url: https://mpr.apollogrp.edu/vagrant/rhel-6.5-x86_64.box
      vagrantfile_erb: "./test/fixtures/vagrantfiles/default-rhel.erb"
      satellite:
        enable: true
suites:
  - name: default
    run_list:
      - recipe[foobar::default]
    attributes:
