AllCops:
  Include:
    - 'Gemfile'
    - 'Berksfile'
  Exclude: []

CyclomaticComplexity:
  Max: 10
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
HashSyntax:
  Enabled: false
AlignParameters:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
Style/StringLiterals:
  Enabled: false
